### ISSUE TITLE
无法配合vite打包

### ISSUE THREAD

**Issue by shuaizai88** [suchjs/such#16]
(this will be run only when your dependencies or config have changed)
 > node_modules/suchjs/lib/node.js:55:17: error: Could not read from file: G:\fhs\fhs-framework\vue_ui\fs.js
    55 │ var fs = require("fs");
       ╵                  ~~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/suchjs/lib/node.js:55:17: error: Could not read from file: G:\fhs\fhs-framework\vue_ui\fs.js
    at failureErrorWithLog (G:\fhs\fhs-framework\vue_ui\node_modules\vite\node_modules\esbuild\lib\main.js:1224:15)
    at buildResponseToResult (G:\fhs\fhs-framework\vue_ui\node_modules\vite\node_modules\esbuild\lib\main.js:9

**Comment by fefit** [comment]
@shuaizai88 感谢反馈，根据您的描述来看，主要的问题在于两个方面：

1、在浏览器端，suchjs引入模块需要用如下方式：
```javascript
// 浏览器端，需要指定suchjs/lib/browser作为导出
import globalSuch, { createNsSuch } from "suchjs/lib/browser";
// 代替node端的方式
// import globalSuch, { createNsSuch } from "suchjs";
```
suchjs在浏览器端和node端有些模拟类型的实现不大一致，在node端支持读取文件等，但在浏览器端目前没有支持。修改这里能解决你在调用时出现引入"fs"等node模块报错的问题。

2、在vite里，模块引入会出现无法找到默认导出的问题
用vite测试了一下，发现使用上面的导出修改仍会有报错，主要的问题在于vite依赖于ESM模块化，但suchjs虽然在node端依赖于package.json的exports做了ESM的兼容写法，但在browser浏览器端没有做对应处理。另外发现vite对于这种兼容写法的包，并不会对相应的引入的cjs模块做预先依赖优化、从而将对应的CommonJS写法转成ESModule写法的处理，[https://github.com/vitejs/vite/issues/3024](https://github.com/vitejs/vite/issues/3024) 可以找到类似的issue。目前的解决方法就是需要在`vite.config.js`的配置文件中，强制让vite进行Pre-Bundling依赖优化，对应配置如下：
```javascript
export default defineConfig({
  // ...其它配置
  optimizeDeps: {
    // 在include中加入"suchjs/lib/browser"
    include: ["suchjs/lib/browser"],
  },
  // ... 其它配置
});
```
通过以上方式就可以正常使用suchjs了，导出的修改将发布一个新版本`3.1.2`，如果使用中仍然遇到问题，欢迎随时反馈~感谢！
